[package]
name = "dollis"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
bevy = { version = "0.8", default-features = false, features = ["x11"] }
bevy_egui = "0.15"
bevy_rapier3d = "0.16"
bevy-inspector-egui = { version = "0.12", default-features = false, features = [
  "clipboard",
  "bevy_pbr",
] }
iyes_loopless = "0.7"
leafwing-input-manager = { version = "0.5", default-features = false }
serde = "1.0"
serde_json = "1.0"
strum = { version = "0.24", features = ["derive"] }
standard_paths = "1.1"
anyhow = "1.0"
tap = "1.0"
