[package]
name = "dollis"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
bevy = { version = "0.8", default-features = false, features = [
  "bevy_gltf",
  "filesystem_watcher",
  "png",
  "x11",
] }
bevy_renet = "0.0.5"
bevy_rapier3d = "0.16"
bevy_mod_raycast = "0.6"
bevy_mod_outline = { version = "0.2", default-features = false }
bevy_egui = "0.16"
bevy-inspector-egui = { version = "0.13", default-features = false, features = [
  "clipboard",
  "bevy_pbr",
] }
bevy-scene-hook = "4.0"
iyes_loopless = "0.7"
leafwing-input-manager = { version = "0.5", default-features = false }
serde = "1.0"
strum = { version = "0.24", features = ["derive"] }
derive_more = { version = "0.99", default-features = false, features = [
  "from",
  "constructor",
] }
standard_paths = "1.1"
clap = { version = "3.2", features = ["derive"] }
anyhow = "1.0"
toml = "0.5"
rmp-serde = "1.1"
ron = "0.7"
tap = "1.0"
once_cell = "1.15"
smallvec = "1.9"
walkdir = "2.3"

[dev-dependencies]
fastrand = "1.8.0"
serde_test = "1.0"
