name: Main
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/dependabot.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/dependabot.yml"
env:
  CARGO_TERM_COLOR: always
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Install Taplo
        run: cargo install taplo-cli

      - name: Format
        run: |
          cargo fmt --check
          taplo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libxcb-shape0-dev libxcb-xfixes0-dev libudev-dev

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Clippy
        run: cargo clippy --no-deps --all-features --tests -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libxcb-shape0-dev libxcb-xfixes0-dev libudev-dev

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Install LLVM tools
        run: rustup component add llvm-tools-preview

      - name: Install Grcov
        run: cargo install grcov

      - name: Install Cargo Make
        run: cargo install cargo-make

      - name: Test
        run: cargo make coverage -o lcov.info

      - name: Upload code coverage results
        if: github.actor != 'dependabot'
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: lcov.info

  codecov:
    name: Upload to Codecov
    if: github.actor != 'dependabot'
    needs: [test, clippy, format]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Download code coverage results
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
